import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'ngd-test-'));
process.env.NGD_DATA_DIR = temporary;
const { app } = await import('../server.mjs');
const server = app.listen(0, '127.0.0.1');
await new Promise(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
after(async () => { await new Promise(resolve => server.close(resolve)); fs.rmSync(temporary, { recursive:true, force:true }); });
const request = async (url, options) => { const response = await fetch(base + url, options); return { status:response.status, body:await response.json() }; };
const json = (method, body, headers={}) => ({ method, headers:{'Content-Type':'application/json', ...headers},body:JSON.stringify(body) });
test('local workflow persists upload and planning, rejects malformed inputs and does not claim publication', async () => {
  const initial = await request('/api/state');
  assert.equal(initial.body.contents.length, 0);
  const invalid = new FormData(); invalid.append('video',new Blob(['not video']),'bad.mp4'); invalid.append('title','Inválido'); invalid.append('channels','[]');
  assert.equal((await request('/api/contents',{method:'POST',body:invalid})).status,400);
  assert.equal(fs.readdirSync(path.join(temporary,'videos')).length,0);
  const fixture = Buffer.alloc(32); fixture.writeUInt32BE(32); fixture.write('ftyp',4); fixture.write('isom',8);
  const upload = new FormData(); upload.append('video',new Blob([fixture],{type:'video/mp4'}),'fixture.mp4'); upload.append('title','Cartões NGD'); upload.append('channels','["youtube"]');
  const saved = await request('/api/contents',{method:'POST',body:upload});
  assert.equal(saved.status,201); assert.equal(saved.body.status,'draft');
  const plan = {title:'Cartões revisados',caption:'Acabamento fosco',channels:['youtube','instagram'],scheduledAt:'2026-10-01T15:00:00.000Z'};
  const edited = await request('/api/contents/'+saved.body.id,json('PATCH',plan));
  assert.equal(edited.body.status,'planned');
  const disk = JSON.parse(fs.readFileSync(path.join(temporary,'dashboard.json'),'utf8'));
  assert.deepEqual(disk.contents[0].channels,plan.channels); assert.equal(disk.contents[0].title,plan.title);
  assert.equal((await fetch(base+'/media/'+saved.body.file,{headers:{Range:'bytes=0-7'}})).status,206);
  assert.equal((await request('/api/contents/'+saved.body.id,json('PATCH',{...plan,channels:['unknown']}))).status,400);
  assert.equal((await request('/api/profiles/youtube',json('PUT',{url:'https://youtube.com.evil.example/channel'}))).status,400);
  assert.equal((await request('/api/profiles/youtube',json('PUT',{url:'https://www.youtube.com/@ngd'}))).body.connected,false);
  assert.equal((await request('/api/settings',json('PUT',{...initial.body.settings,n8nUrl:'https://external.example'}))).status,400);
  assert.equal((await request('/api/settings',json('PUT',initial.body.settings,{Origin:'https://evil.example'}))).status,403);
  const foreignHostStatus = await new Promise((resolve,reject) => { http.get(base+'/api/state',{headers:{Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);}).on('error',reject); });
  assert.equal(foreignHostStatus,403);
  assert.equal((await request('/api/export')).body.contents[0].status,'planned');
  assert.equal((await request('/api/automation/prepare',{method:'POST'})).status,401);
  const token = 'test-local-bridge-token';
  fs.writeFileSync(path.join(temporary,'automation-secrets.json'),JSON.stringify({bridgeToken:token}));
  const prepare = await request('/api/automation/prepare',{method:'POST',headers:{'X-NGD-Automation':token}});
  assert.equal(prepare.body.total,2); assert.equal(prepare.body.published,0);
  await request('/api/automation/prepare',{method:'POST',headers:{'X-NGD-Automation':token}});
  const reconciled = await request('/api/state');
  assert.equal(reconciled.body.automation.jobs.length,2);
  assert.equal(reconciled.body.contents[0].status,'planned');
  assert.equal(JSON.stringify(reconciled.body).includes(token),false);
});
